/* $Id: includes.hpp,v 1.8 1999/06/08 15:36:45 oliver Exp $
 * Standard/global includes
 */

#ifndef INCS_H
#define INCS_H	1

/* Most importantly, what has 'autoconf' taught us? */
#ifdef HAVE_CONFIG_H
# include "config.h"            /* Generated by autoconf */
#else
# error "config.h is required - panic!"
#endif

/* Standard, system includes */

#include <sys/types.h>
#ifdef HAVE_UNISTD_H
# include <unistd.h>
#endif
#include <stdio.h>
#include <ctype.h>
#ifdef STDC_HEADERS
# include <string.h>
# include <stdlib.h>
# include <stdarg.h>
#endif
#ifdef HAVE_MEMORY_H
# include <memory.h>
#endif
#ifdef HAVE_FCNTL_H
# include <fcntl.h>
#endif
#include <errno.h>

#include "portable.hpp"

#include "assert.h"


#endif				/* INCS_H */
