actions.o: actions.cc ../h/includes.hpp ../h/config.h \
 ../h/portable.hpp /usr/include/assert.h ../h/structs.hpp \
 ../h/defines.hpp ../h/typedefs.hpp ../h/cl_basicobj.hpp \
 ../h/cl_player.hpp ../h/cl_room.hpp ../h/cl_object.hpp
classes.o: classes.cc ../h/includes.hpp ../h/config.h \
 ../h/portable.hpp /usr/include/assert.h ../h/structs.hpp \
 ../h/defines.hpp ../h/typedefs.hpp ../h/cl_basicobj.hpp \
 ../h/cl_player.hpp ../h/cl_room.hpp ../h/cl_object.hpp
conditions.o: conditions.cc ../h/includes.hpp ../h/config.h \
 ../h/portable.hpp /usr/include/assert.h ../h/structs.hpp \
 ../h/defines.hpp ../h/typedefs.hpp ../h/cl_basicobj.hpp \
 ../h/cl_player.hpp ../h/cl_room.hpp ../h/cl_object.hpp
data.o: data.cc ../h/includes.hpp ../h/config.h ../h/portable.hpp \
 /usr/include/assert.h ../h/typedefs.hpp ../h/defines.hpp \
 ../h/actuals.hpp
misc.o: misc.cc ../h/includes.hpp ../h/config.h ../h/portable.hpp \
 /usr/include/assert.h ../h/libprotos.hpp ../h/variables.hpp
vocab.o: vocab.cc ../h/includes.hpp ../h/config.h ../h/portable.hpp \
 /usr/include/assert.h ../h/defines.hpp ../h/typedefs.hpp \
 ../h/vocab.hpp ../h/structs.hpp ../h/cl_basicobj.hpp \
 ../h/cl_player.hpp ../h/cl_room.hpp ../h/cl_object.hpp
