#ifndef AMUL_AMAN_VERSION_H
#define AMUL_AMAN_VERSION_H

#define AMAN_VERSION 0
#define AMAN_REVISION 590
#define AMAN_DATE "29.5.91"
#define AMAN_VERS "AMAN 0.590"
#define AMAN_VSTRING "AMAN 0.590 (29.5.91)"

#endif  // AMUL_AMAN_VERSION_H
