basicobjs.o: basicobjs.cc smuglcom.hpp ../h/includes.hpp ../h/config.h \
 ../h/portable.hpp /usr/include/assert.h ../h/structs.hpp \
 ../h/defines.hpp ../h/typedefs.hpp ../h/cl_basicobj.hpp \
 ../h/cl_player.hpp ../h/cl_room.hpp ../h/cl_object.hpp \
 ../h/variables.hpp ../h/consts.hpp protos.hpp ../h/vocab.hpp \
 ../h/libprotos.hpp
cleanup.o: cleanup.cc smuglcom.hpp ../h/includes.hpp ../h/config.h \
 ../h/portable.hpp /usr/include/assert.h ../h/structs.hpp \
 ../h/defines.hpp ../h/typedefs.hpp ../h/cl_basicobj.hpp \
 ../h/cl_player.hpp ../h/cl_room.hpp ../h/cl_object.hpp \
 ../h/variables.hpp ../h/consts.hpp protos.hpp ../h/vocab.hpp
errors.o: errors.cc smuglcom.hpp ../h/includes.hpp ../h/config.h \
 ../h/portable.hpp /usr/include/assert.h ../h/structs.hpp \
 ../h/defines.hpp ../h/typedefs.hpp ../h/cl_basicobj.hpp \
 ../h/cl_player.hpp ../h/cl_room.hpp ../h/cl_object.hpp \
 ../h/variables.hpp ../h/consts.hpp protos.hpp ../h/vocab.hpp \
 ../h/libprotos.hpp
filebits.o: filebits.cc smuglcom.hpp ../h/includes.hpp ../h/config.h \
 ../h/portable.hpp /usr/include/assert.h ../h/structs.hpp \
 ../h/defines.hpp ../h/typedefs.hpp ../h/cl_basicobj.hpp \
 ../h/cl_player.hpp ../h/cl_room.hpp ../h/cl_object.hpp \
 ../h/variables.hpp ../h/consts.hpp protos.hpp ../h/vocab.hpp \
 ../h/libprotos.hpp
langproc.o: langproc.cc smuglcom.hpp ../h/includes.hpp ../h/config.h \
 ../h/portable.hpp /usr/include/assert.h ../h/structs.hpp \
 ../h/defines.hpp ../h/typedefs.hpp ../h/cl_basicobj.hpp \
 ../h/cl_player.hpp ../h/cl_room.hpp ../h/cl_object.hpp \
 ../h/variables.hpp ../h/consts.hpp protos.hpp ../h/vocab.hpp \
 ../h/actuals.hpp
misc.o: misc.cc smuglcom.hpp ../h/includes.hpp ../h/config.h \
 ../h/portable.hpp /usr/include/assert.h ../h/structs.hpp \
 ../h/defines.hpp ../h/typedefs.hpp ../h/cl_basicobj.hpp \
 ../h/cl_player.hpp ../h/cl_room.hpp ../h/cl_object.hpp \
 ../h/variables.hpp ../h/consts.hpp protos.hpp ../h/vocab.hpp
mobproc.o: mobproc.cc smuglcom.hpp ../h/includes.hpp ../h/config.h \
 ../h/portable.hpp /usr/include/assert.h ../h/structs.hpp \
 ../h/defines.hpp ../h/typedefs.hpp ../h/cl_basicobj.hpp \
 ../h/cl_player.hpp ../h/cl_room.hpp ../h/cl_object.hpp \
 ../h/variables.hpp ../h/consts.hpp protos.hpp ../h/vocab.hpp
msgmgt.o: msgmgt.cc smuglcom.hpp ../h/includes.hpp ../h/config.h \
 ../h/portable.hpp /usr/include/assert.h ../h/structs.hpp \
 ../h/defines.hpp ../h/typedefs.hpp ../h/cl_basicobj.hpp \
 ../h/cl_player.hpp ../h/cl_room.hpp ../h/cl_object.hpp \
 ../h/variables.hpp ../h/consts.hpp protos.hpp ../h/vocab.hpp \
 ../h/libprotos.hpp
obdsproc.o: obdsproc.cc smuglcom.hpp ../h/includes.hpp ../h/config.h \
 ../h/portable.hpp /usr/include/assert.h ../h/structs.hpp \
 ../h/defines.hpp ../h/typedefs.hpp ../h/cl_basicobj.hpp \
 ../h/cl_player.hpp ../h/cl_room.hpp ../h/cl_object.hpp \
 ../h/variables.hpp ../h/consts.hpp protos.hpp ../h/vocab.hpp
objproc.o: objproc.cc smuglcom.hpp ../h/includes.hpp ../h/config.h \
 ../h/portable.hpp /usr/include/assert.h ../h/structs.hpp \
 ../h/defines.hpp ../h/typedefs.hpp ../h/cl_basicobj.hpp \
 ../h/cl_player.hpp ../h/cl_room.hpp ../h/cl_object.hpp \
 ../h/variables.hpp ../h/consts.hpp protos.hpp ../h/vocab.hpp
roomproc.o: roomproc.cc smuglcom.hpp ../h/includes.hpp ../h/config.h \
 ../h/portable.hpp /usr/include/assert.h ../h/structs.hpp \
 ../h/defines.hpp ../h/typedefs.hpp ../h/cl_basicobj.hpp \
 ../h/cl_player.hpp ../h/cl_room.hpp ../h/cl_object.hpp \
 ../h/variables.hpp ../h/consts.hpp protos.hpp ../h/vocab.hpp
smsgproc.o: smsgproc.cc smuglcom.hpp ../h/includes.hpp ../h/config.h \
 ../h/portable.hpp /usr/include/assert.h ../h/structs.hpp \
 ../h/defines.hpp ../h/typedefs.hpp ../h/cl_basicobj.hpp \
 ../h/cl_player.hpp ../h/cl_room.hpp ../h/cl_object.hpp \
 ../h/variables.hpp ../h/consts.hpp protos.hpp ../h/vocab.hpp
smuglcom.o: smuglcom.cc smuglcom.hpp ../h/includes.hpp ../h/config.h \
 ../h/portable.hpp /usr/include/assert.h ../h/structs.hpp \
 ../h/defines.hpp ../h/typedefs.hpp ../h/cl_basicobj.hpp \
 ../h/cl_player.hpp ../h/cl_room.hpp ../h/cl_object.hpp \
 ../h/variables.hpp ../h/consts.hpp protos.hpp ../h/vocab.hpp \
 ../h/actuals.hpp virtuals.hpp
synsproc.o: synsproc.cc smuglcom.hpp ../h/includes.hpp ../h/config.h \
 ../h/portable.hpp /usr/include/assert.h ../h/structs.hpp \
 ../h/defines.hpp ../h/typedefs.hpp ../h/cl_basicobj.hpp \
 ../h/cl_player.hpp ../h/cl_room.hpp ../h/cl_object.hpp \
 ../h/variables.hpp ../h/consts.hpp protos.hpp ../h/vocab.hpp
titleproc.o: titleproc.cc smuglcom.hpp ../h/includes.hpp ../h/config.h \
 ../h/portable.hpp /usr/include/assert.h ../h/structs.hpp \
 ../h/defines.hpp ../h/typedefs.hpp ../h/cl_basicobj.hpp \
 ../h/cl_player.hpp ../h/cl_room.hpp ../h/cl_object.hpp \
 ../h/variables.hpp ../h/consts.hpp protos.hpp ../h/vocab.hpp
travfunc.o: travfunc.cc smuglcom.hpp ../h/includes.hpp ../h/config.h \
 ../h/portable.hpp /usr/include/assert.h ../h/structs.hpp \
 ../h/defines.hpp ../h/typedefs.hpp ../h/cl_basicobj.hpp \
 ../h/cl_player.hpp ../h/cl_room.hpp ../h/cl_object.hpp \
 ../h/variables.hpp ../h/consts.hpp protos.hpp ../h/vocab.hpp \
 ../h/actuals.hpp
travproc.o: travproc.cc smuglcom.hpp ../h/includes.hpp ../h/config.h \
 ../h/portable.hpp /usr/include/assert.h ../h/structs.hpp \
 ../h/defines.hpp ../h/typedefs.hpp ../h/cl_basicobj.hpp \
 ../h/cl_player.hpp ../h/cl_room.hpp ../h/cl_object.hpp \
 ../h/variables.hpp ../h/consts.hpp protos.hpp ../h/vocab.hpp
umsgproc.o: umsgproc.cc smuglcom.hpp ../h/includes.hpp ../h/config.h \
 ../h/portable.hpp /usr/include/assert.h ../h/structs.hpp \
 ../h/defines.hpp ../h/typedefs.hpp ../h/cl_basicobj.hpp \
 ../h/cl_player.hpp ../h/cl_room.hpp ../h/cl_object.hpp \
 ../h/variables.hpp ../h/consts.hpp protos.hpp ../h/vocab.hpp
verify.o: verify.cc smuglcom.hpp ../h/includes.hpp ../h/config.h \
 ../h/portable.hpp /usr/include/assert.h ../h/structs.hpp \
 ../h/defines.hpp ../h/typedefs.hpp ../h/cl_basicobj.hpp \
 ../h/cl_player.hpp ../h/cl_room.hpp ../h/cl_object.hpp \
 ../h/variables.hpp ../h/consts.hpp protos.hpp ../h/vocab.hpp \
 virtuals.hpp
version.o: version.cc smuglcom.hpp ../h/includes.hpp ../h/config.h \
 ../h/portable.hpp /usr/include/assert.h ../h/structs.hpp \
 ../h/defines.hpp ../h/typedefs.hpp ../h/cl_basicobj.hpp \
 ../h/cl_player.hpp ../h/cl_room.hpp ../h/cl_object.hpp \
 ../h/variables.hpp ../h/consts.hpp protos.hpp ../h/vocab.hpp \
 ../h/SMUGLCOM.h
vocab.o: vocab.cc ../h/includes.hpp ../h/config.h ../h/portable.hpp \
 /usr/include/assert.h ../h/structs.hpp ../h/defines.hpp \
 ../h/typedefs.hpp ../h/cl_basicobj.hpp ../h/cl_player.hpp \
 ../h/cl_room.hpp ../h/cl_object.hpp ../h/vocab.hpp protos.hpp \
 ../h/libprotos.hpp
