aliases.o: aliases.cc smugl.hpp ../h/includes.hpp ../h/config.h \
 ../h/portable.hpp /usr/include/assert.h ../h/structs.hpp \
 ../h/defines.hpp ../h/typedefs.hpp ../h/cl_basicobj.hpp \
 ../h/cl_player.hpp ../h/cl_room.hpp ../h/cl_object.hpp ../h/vocab.hpp \
 data.hpp basicobjs.hpp players.hpp textproc.hpp aliases.hpp
basicobjs.o: basicobjs.cc smugl.hpp ../h/includes.hpp ../h/config.h \
 ../h/portable.hpp /usr/include/assert.h ../h/structs.hpp \
 ../h/defines.hpp ../h/typedefs.hpp ../h/cl_basicobj.hpp \
 ../h/cl_player.hpp ../h/cl_room.hpp ../h/cl_object.hpp ../h/vocab.hpp \
 data.hpp basicobjs.hpp players.hpp textproc.hpp
client.o: client.cc smugl.hpp ../h/includes.hpp ../h/config.h \
 ../h/portable.hpp /usr/include/assert.h ../h/structs.hpp \
 ../h/defines.hpp ../h/typedefs.hpp ../h/cl_basicobj.hpp \
 ../h/cl_player.hpp ../h/cl_room.hpp ../h/cl_object.hpp ../h/vocab.hpp \
 data.hpp basicobjs.hpp players.hpp textproc.hpp misc.hpp ipc.hpp \
 io.hpp
io.o: io.cc smugl.hpp ../h/includes.hpp ../h/config.h \
 ../h/portable.hpp /usr/include/assert.h ../h/structs.hpp \
 ../h/defines.hpp ../h/typedefs.hpp ../h/cl_basicobj.hpp \
 ../h/cl_player.hpp ../h/cl_room.hpp ../h/cl_object.hpp ../h/vocab.hpp \
 data.hpp basicobjs.hpp players.hpp textproc.hpp client.hpp misc.hpp \
 ipc.hpp io.hpp
ipc.o: ipc.cc smugl.hpp ../h/includes.hpp ../h/config.h \
 ../h/portable.hpp /usr/include/assert.h ../h/structs.hpp \
 ../h/defines.hpp ../h/typedefs.hpp ../h/cl_basicobj.hpp \
 ../h/cl_player.hpp ../h/cl_room.hpp ../h/cl_object.hpp ../h/vocab.hpp \
 data.hpp basicobjs.hpp players.hpp textproc.hpp manager.hpp ipc.hpp \
 io.hpp rooms.hpp
lang.o: lang.cc smugl.hpp ../h/includes.hpp ../h/config.h \
 ../h/portable.hpp /usr/include/assert.h ../h/structs.hpp \
 ../h/defines.hpp ../h/typedefs.hpp ../h/cl_basicobj.hpp \
 ../h/cl_player.hpp ../h/cl_room.hpp ../h/cl_object.hpp ../h/vocab.hpp \
 data.hpp basicobjs.hpp players.hpp textproc.hpp aliases.hpp lang.hpp \
 rooms.hpp parser.hpp
langtable.o: langtable.cc smugl.hpp ../h/includes.hpp ../h/config.h \
 ../h/portable.hpp /usr/include/assert.h ../h/structs.hpp \
 ../h/defines.hpp ../h/typedefs.hpp ../h/cl_basicobj.hpp \
 ../h/cl_player.hpp ../h/cl_room.hpp ../h/cl_object.hpp ../h/vocab.hpp \
 data.hpp basicobjs.hpp players.hpp textproc.hpp aliases.hpp lang.hpp \
 rooms.hpp parser.hpp io.hpp langtable.hpp
loaders.o: loaders.cc smugl.hpp ../h/includes.hpp ../h/config.h \
 ../h/portable.hpp /usr/include/assert.h ../h/structs.hpp \
 ../h/defines.hpp ../h/typedefs.hpp ../h/cl_basicobj.hpp \
 ../h/cl_player.hpp ../h/cl_room.hpp ../h/cl_object.hpp ../h/vocab.hpp \
 data.hpp basicobjs.hpp players.hpp textproc.hpp ../h/consts.hpp \
 misc.hpp io.hpp ../h/libprotos.hpp ranks.hpp rooms.hpp mobiles.hpp \
 objects.hpp lang.hpp travel.hpp aliases.hpp manager.hpp
login.o: login.cc smugl.hpp ../h/includes.hpp ../h/config.h \
 ../h/portable.hpp /usr/include/assert.h ../h/structs.hpp \
 ../h/defines.hpp ../h/typedefs.hpp ../h/cl_basicobj.hpp \
 ../h/cl_player.hpp ../h/cl_room.hpp ../h/cl_object.hpp ../h/vocab.hpp \
 data.hpp basicobjs.hpp players.hpp textproc.hpp ../h/consts.hpp \
 ../h/libprotos.hpp ranks.hpp rooms.hpp io.hpp ipc.hpp misc.hpp
manager.o: manager.cc smugl.hpp ../h/includes.hpp ../h/config.h \
 ../h/portable.hpp /usr/include/assert.h ../h/structs.hpp \
 ../h/defines.hpp ../h/typedefs.hpp ../h/cl_basicobj.hpp \
 ../h/cl_player.hpp ../h/cl_room.hpp ../h/cl_object.hpp ../h/vocab.hpp \
 data.hpp basicobjs.hpp players.hpp textproc.hpp ../h/variables.hpp \
 ../h/consts.hpp ../h/libprotos.hpp misc.hpp ipc.hpp io.hpp rooms.hpp \
 objects.hpp
misc.o: misc.cc smugl.hpp ../h/includes.hpp ../h/config.h \
 ../h/portable.hpp /usr/include/assert.h ../h/structs.hpp \
 ../h/defines.hpp ../h/typedefs.hpp ../h/cl_basicobj.hpp \
 ../h/cl_player.hpp ../h/cl_room.hpp ../h/cl_object.hpp ../h/vocab.hpp \
 data.hpp basicobjs.hpp players.hpp textproc.hpp ../h/libprotos.hpp \
 io.hpp
mobiles.o: mobiles.cc smugl.hpp ../h/includes.hpp ../h/config.h \
 ../h/portable.hpp /usr/include/assert.h ../h/structs.hpp \
 ../h/defines.hpp ../h/typedefs.hpp ../h/cl_basicobj.hpp \
 ../h/cl_player.hpp ../h/cl_room.hpp ../h/cl_object.hpp ../h/vocab.hpp \
 data.hpp basicobjs.hpp players.hpp textproc.hpp mobiles.hpp rooms.hpp
objects.o: objects.cc smugl.hpp ../h/includes.hpp ../h/config.h \
 ../h/portable.hpp /usr/include/assert.h ../h/structs.hpp \
 ../h/defines.hpp ../h/typedefs.hpp ../h/cl_basicobj.hpp \
 ../h/cl_player.hpp ../h/cl_room.hpp ../h/cl_object.hpp ../h/vocab.hpp \
 data.hpp basicobjs.hpp players.hpp textproc.hpp ../h/consts.hpp \
 objects.hpp rooms.hpp
parser.o: parser.cc smugl.hpp ../h/includes.hpp ../h/config.h \
 ../h/portable.hpp /usr/include/assert.h ../h/structs.hpp \
 ../h/defines.hpp ../h/typedefs.hpp ../h/cl_basicobj.hpp \
 ../h/cl_player.hpp ../h/cl_room.hpp ../h/cl_object.hpp ../h/vocab.hpp \
 data.hpp basicobjs.hpp players.hpp textproc.hpp parser.hpp ipc.hpp \
 ranks.hpp aliases.hpp rooms.hpp lang.hpp langtable.hpp \
 ../h/consts.hpp
players.o: players.cc smugl.hpp ../h/includes.hpp ../h/config.h \
 ../h/portable.hpp /usr/include/assert.h ../h/structs.hpp \
 ../h/defines.hpp ../h/typedefs.hpp ../h/cl_basicobj.hpp \
 ../h/cl_player.hpp ../h/cl_room.hpp ../h/cl_object.hpp ../h/vocab.hpp \
 data.hpp basicobjs.hpp players.hpp textproc.hpp ../h/consts.hpp \
 rooms.hpp ipc.hpp ranks.hpp
ranks.o: ranks.cc smugl.hpp ../h/includes.hpp ../h/config.h \
 ../h/portable.hpp /usr/include/assert.h ../h/structs.hpp \
 ../h/defines.hpp ../h/typedefs.hpp ../h/cl_basicobj.hpp \
 ../h/cl_player.hpp ../h/cl_room.hpp ../h/cl_object.hpp ../h/vocab.hpp \
 data.hpp basicobjs.hpp players.hpp textproc.hpp ranks.hpp
rooms.o: rooms.cc smugl.hpp ../h/includes.hpp ../h/config.h \
 ../h/portable.hpp /usr/include/assert.h ../h/structs.hpp \
 ../h/defines.hpp ../h/typedefs.hpp ../h/cl_basicobj.hpp \
 ../h/cl_player.hpp ../h/cl_room.hpp ../h/cl_object.hpp ../h/vocab.hpp \
 data.hpp basicobjs.hpp players.hpp textproc.hpp ../h/consts.hpp \
 misc.hpp lang.hpp rooms.hpp travel.hpp objects.hpp ipc.hpp
smugl.o: smugl.cc smugl.hpp ../h/includes.hpp ../h/config.h \
 ../h/portable.hpp /usr/include/assert.h ../h/structs.hpp \
 ../h/defines.hpp ../h/typedefs.hpp ../h/cl_basicobj.hpp \
 ../h/cl_player.hpp ../h/cl_room.hpp ../h/cl_object.hpp ../h/vocab.hpp \
 data.hpp basicobjs.hpp players.hpp textproc.hpp \
 /usr/include/sys/stat.h /usr/include/sys/param.h ../h/consts.hpp \
 loaders.hpp client.hpp ../h/libprotos.hpp lang.hpp rooms.hpp \
 ranks.hpp mobiles.hpp objects.hpp manager.hpp travel.hpp ipc.hpp \
 io.hpp misc.hpp login.hpp parser.hpp
textproc.o: textproc.cc smugl.hpp ../h/includes.hpp ../h/config.h \
 ../h/portable.hpp /usr/include/assert.h ../h/structs.hpp \
 ../h/defines.hpp ../h/typedefs.hpp ../h/cl_basicobj.hpp \
 ../h/cl_player.hpp ../h/cl_room.hpp ../h/cl_object.hpp ../h/vocab.hpp \
 data.hpp basicobjs.hpp players.hpp textproc.hpp ../h/actuals.hpp \
 rooms.hpp ranks.hpp parser.hpp
travel.o: travel.cc smugl.hpp ../h/includes.hpp ../h/config.h \
 ../h/portable.hpp /usr/include/assert.h ../h/structs.hpp \
 ../h/defines.hpp ../h/typedefs.hpp ../h/cl_basicobj.hpp \
 ../h/cl_player.hpp ../h/cl_room.hpp ../h/cl_object.hpp ../h/vocab.hpp \
 data.hpp basicobjs.hpp players.hpp textproc.hpp travel.hpp rooms.hpp
version.o: version.cc ../h/SMUGL.h /usr/include/stdio.h
