#pragma once
/*
 * Standard/global includes
 */

// Configuration generated by CMake
#include "config.h"

/* Standard, system includes */

#include <sys/types.h>
#ifdef HAVE_UNISTD_H
# include <unistd.h>
#endif
#include <stdio.h>
#include <ctype.h>
#include <string.h>
#include <stdlib.h>
#include <stdarg.h>
#ifdef HAVE_MEMORY_H
# include <memory.h>
#endif
#ifdef HAVE_FCNTL_H
# include <fcntl.h>
#endif
#include <errno.h>

#include "include/portable.hpp"

#include <assert.h>
