#ifndef H_AMULCOM_H
#define H_AMULCOM_H

#define AMULCOM_VERSION 0
#define AMULCOM_REVISION 8992
#define AMULCOM_DATE "29.5.91"
#define AMULCOM_VERS "AMULCOM 0.8992"
#define AMULCOM_VSTRING "AMULCOM 0.8992 (29.5.91)"

#endif  // H_AMULCOM_H
